### ISSUE TITLE
怎么训练2.5D P-Unet

### ISSUE THREAD

**Issue by Xuying301** [davidlinhl/liverSeg#11]
作者你好，请问怎样可以训练2.5D P-Unet项目？

**Comment by linhandev** [comment]
你好，这个项目有段时没更新了，各种依赖都升级了应该不太好调通。建议试试 paddleseg 和 medicalseg

https://github.com/PaddlePaddle/PaddleSeg

https://github.com/PaddleCV-SIG/MedicalSeg
